import type { TranscriptMessage } from "@/types";

export const PHASE2_MESSAGES: TranscriptMessage[] = [
  {
    id: 1,
    role: "assistant",
    speaker: "BiteBridge Ops AI",
    content: "Morning, Priya. Ops monitoring is live. I'll flag anything anomalous across order, payment, and driver systems.",
    tokenCount: 18,
    priority: "P3",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 2,
    role: "user",
    speaker: "Priya (Ops Manager)",
    content: "Thanks. Keep an eye on the evening rush — last Friday had some delivery lag. I'm covering the afternoon shift.",
    tokenCount: 22,
    priority: "P3",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 3,
    role: "assistant",
    speaker: "BiteBridge Ops AI",
    content: "Noted. Monitoring order queue depth, driver availability, and payment success rates in real time.",
    tokenCount: 16,
    priority: "P3",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 4,
    role: "tool",
    speaker: "order_dashboard",
    content: `{"query":"order_metrics","results":{"queue_depth":150,"avg_prep_min":12,"orders_per_min":86,"active_orders":520}}`,
    tokenCount: 42,
    priority: "P2",
    isToolResult: true,
    toolResultSummary: "Order metrics nominal: queue 150, avg prep 12min.",
    keyFactIds: [],
  },
  {
    id: 5,
    role: "user",
    speaker: "Priya (Ops Manager)",
    content: "Queue looks healthy. Let's keep lunch running smoothly — boxed lunch promo goes live at noon.",
    tokenCount: 20,
    priority: "P3",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 6,
    role: "assistant",
    speaker: "BiteBridge Ops AI",
    content: "WARNING: Order processing backup detected. Queue depth climbed from 150 to 387 in 5 minutes. Order acceptance has stalled.",
    tokenCount: 24,
    priority: "P1",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 7,
    role: "tool",
    speaker: "order_pipeline",
    content: `{"query":"pipeline_status","results":{"processing_rate":0,"queue_depth":387,"stalled_at":"checkout","error":"DB connection pool exhausted","retries":48}}`,
    tokenCount: 56,
    priority: "P1",
    isToolResult: true,
    toolResultSummary: "Pipeline stalled at checkout — DB connection pool exhausted.",
    keyFactIds: [],
  },
  {
    id: 8,
    role: "assistant",
    speaker: "BiteBridge Ops AI",
    content: "Root cause: database connection pool exhausted at checkout. Retrying with backoff; scaling connection pool by 3x.",
    tokenCount: 20,
    priority: "P1",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 9,
    role: "user",
    speaker: "Priya (Ops Manager)",
    content: "Good catch. Scale the pool and verify orders start flowing again. I'll notify the on-call DB engineer.",
    tokenCount: 21,
    priority: "P1",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 10,
    role: "assistant",
    speaker: "BiteBridge Ops AI",
    content: "Order backup resolved. Queue drained from 387 to 62. Checkout processing restored to normal throughput.",
    tokenCount: 19,
    priority: "P1",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 11,
    role: "user",
    speaker: "Priya (Ops Manager)",
    content: "Order backlog resolved. Moving on to review payment reports from the morning.",
    tokenCount: 16,
    priority: "P2",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 12,
    role: "assistant",
    speaker: "BiteBridge Ops AI",
    content: "Scanning payment transactions for anomalies. Checking success rate and duplicate charges.",
    tokenCount: 17,
    priority: "P2",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 13,
    role: "tool",
    speaker: "payment_processor",
    content: `{"query":"payment_anomalies","results":{"double_charges":124,"success_rate":0.68,"duplicate_window_sec":0.4,"affected_users":112}}`,
    tokenCount: 48,
    priority: "P1",
    isToolResult: true,
    toolResultSummary: "124 double charges detected; payment success rate 68%.",
    keyFactIds: [],
  },
  {
    id: 14,
    role: "assistant",
    speaker: "BiteBridge Ops AI",
    content: "Payment double-charge detected: 124 customers charged twice due to a retry race condition on failed checkout. Issuing refunds.",
    tokenCount: 22,
    priority: "P1",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 15,
    role: "user",
    speaker: "Priya (Ops Manager)",
    content: "Refund those immediately and disable the retry-on-failure flag until the race condition is patched.",
    tokenCount: 18,
    priority: "P1",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 16,
    role: "assistant",
    speaker: "BiteBridge Ops AI",
    content: "Refunds processed for all 124 double charges. Retry flag disabled. Payment success rate back to 99%.",
    tokenCount: 19,
    priority: "P1",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 17,
    role: "user",
    speaker: "Priya (Ops Manager)",
    content: "Payments resolved. That was close — lucky it was caught early. Anything from the driver fleet?",
    tokenCount: 18,
    priority: "P2",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 18,
    role: "assistant",
    speaker: "BiteBridge Ops AI",
    content: "Checking driver pool health and dispatch integrity across all zones.",
    tokenCount: 14,
    priority: "P2",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 19,
    role: "tool",
    speaker: "driver_telemetry",
    content: `{"query":"driver_status","results":{"crash_signals":18,"drivers_offline":9,"app_version":"3.4.1","error":"location SDK deadlock","zones_affected":["North","East"]}}`,
    tokenCount: 58,
    priority: "P1",
    isToolResult: true,
    toolResultSummary: "18 crash signals — app 3.4.1 deadlock on location SDK.",
    keyFactIds: [],
  },
  {
    id: 20,
    role: "assistant",
    speaker: "BiteBridge Ops AI",
    content: "Driver app crash detected: version 3.4.1 deadlocks on the location SDK. 9 drivers offline in North/East zones.",
    tokenCount: 20,
    priority: "P1",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 21,
    role: "user",
    speaker: "Priya (Ops Manager)",
    content: "Push the rollback to 3.4.0 and have the mobile team investigate the SDK deadlock.",
    tokenCount: 16,
    priority: "P1",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 22,
    role: "assistant",
    speaker: "BiteBridge Ops AI",
    content: "Rollback to 3.4.0 complete. 9 drivers back online. Crash signals stopped.",
    tokenCount: 16,
    priority: "P1",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 23,
    role: "user",
    speaker: "Priya (Ops Manager)",
    content: "Great. All three incidents handled: order backup, payment double-charges, and driver app crash.",
    tokenCount: 18,
    priority: "P2",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 24,
    role: "assistant",
    speaker: "BiteBridge Ops AI",
    content: "Summary: (1) Order backup from DB pool exhaustion, (2) Payment double-charges from retry race, (3) Driver app crash from location SDK.",
    tokenCount: 26,
    priority: "P2",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 25,
    role: "user",
    speaker: "Priya (Ops Manager)",
    content: "Were these three issues actually related, or did they happen to coincide?",
    tokenCount: 17,
    priority: "P2",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 26,
    role: "assistant",
    speaker: "BiteBridge Ops AI",
    content: "Correlating timestamps: DB pool exhaustion and driver app crash both began ~5 minutes after the boxed lunch promo launch.",
    tokenCount: 20,
    priority: "P2",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 27,
    role: "tool",
    speaker: "monitoring_links",
    content: `{"query":"event_correlation","results":{"promo_launch":"12:00","db_pool_exhaustion":"12:02","payment_race":"12:05","driver_crash":"12:06","shared_resource":"promo traffic spike","link":"yes"}}`,
    tokenCount: 52,
    priority: "P2",
    isToolResult: true,
    toolResultSummary: "All three tied to 12:00 promo traffic spike.",
    keyFactIds: [],
  },
  {
    id: 28,
    role: "assistant",
    speaker: "BiteBridge Ops AI",
    content: "Yes, all three were linked. The boxed lunch promo traffic spike overwhelmed the DB pool, triggered the payment retry race, and crashed the driver SDK under load.",
    tokenCount: 24,
    priority: "P2",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 29,
    role: "user",
    speaker: "Priya (Ops Manager)",
    content: "That's the root cause — promo launch without load testing. Let's require load testing before any promo launch.",
    tokenCount: 20,
    priority: "P2",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 30,
    role: "assistant",
    speaker: "BiteBridge Ops AI",
    content: "Action created: require load testing for all promo launches. Adding to the ops checklist.",
    tokenCount: 17,
    priority: "P2",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 31,
    role: "user",
    speaker: "Priya (Ops Manager)",
    content: "Also file a follow-up to patch the payment retry race condition and the driver location SDK deadlock.",
    tokenCount: 18,
    priority: "P2",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 32,
    role: "assistant",
    speaker: "BiteBridge Ops AI",
    content: "Follow-ups filed: patch retry race condition, fix location SDK deadlock, add load testing gate for promos.",
    tokenCount: 18,
    priority: "P2",
    isToolResult: false,
    keyFactIds: [],
  },
  {
    id: 33,
    role: "user",
    speaker: "Priya (Ops Manager)",
    content: "Session complete. Great work today — we caught all three issues before the evening rush.",
    tokenCount: 20,
    priority: "P3",
    isToolResult: false,
    keyFactIds: [],
  },
];

export const QUALITY_CHECKPOINTS = [
  {
    question: "What caused the order processing backup?",
    reliesOn: [6, 7],
  },
  {
    question: "How was the order backlog resolved?",
    reliesOn: [7, 8, 9],
  },
  {
    question: "What caused the payment double-charges?",
    reliesOn: [13, 14],
  },
  {
    question: "Were the three issues related?",
    reliesOn: [27, 28],
  },
  {
    question: "Why did the driver app crash?",
    reliesOn: [19, 20],
  },
];
